# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

# enable Docker for your repository
options:
  docker: true

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export IMAGE_NAME=dr.haak.co/debian-stretch-php7-apache
          - export IMAGE_NAME_COMMIT=${IMAGE_NAME}:$BITBUCKET_COMMIT
          - export IMAGE_NAME_DATE=${IMAGE_NAME}:$(date +"%Y%m%d%H%M")
          - export IMAGE_NAME_LATEST=${IMAGE_NAME}:latest

          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build --pull -t $IMAGE_NAME_COMMIT .
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD https://dr.haak.co
          # push the new Docker image to the Docker registry
          - docker tag $IMAGE_NAME_COMMIT ${IMAGE_NAME_DATE}
          - docker tag $IMAGE_NAME_COMMIT ${IMAGE_NAME_LATEST}
          #- docker push $IMAGE_NAME_COMMIT
          #- docker push ${IMAGE_NAME_DATE}
          - docker push ${IMAGE_NAME_LATEST}
